framework:
    annotations:
            enabled: false
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    session:
        handler_id: null
        cookie_secure: false # Désactive les cookies sécurisés
    http_method_override: true
