nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:3000']   # Autoriser React à accéder à l'API
        allow_headers: ['Content-Type', 'Authorization', 'Accept']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS']
    paths:
        '^/api/':  # Cela permet de définir les règles CORS uniquement pour les routes API
            allow_origin: ['http://localhost:3000']
